num_arr = list()
number = input("Enter the number of elements you want:")
print ('Enter numbers in array: ')
for i in range(int(number)):
    n = int(input("number :"))
    num_arr.append(int(n))
print ('ARRAY: ',num_arr)
num_arr.sort()
k = int(input("Enter the kth number"))
print ('element',num_arr[k-1])
