number_array = list()
number = input("Enter the number of elements you want:")
print ('Enter numbers in array: ')
for i in range(int(number)):
    n = int(input("number :"))
    number_array.append(int(n))
print ('ARRAY: ',number_array)
number_array.sort()
k = int(input("Enter the kth number"))
print ('element',number_array[k-1])
